### ISSUE TITLE
SchemaParser.ParseError.unsupportedType

### ISSUE THREAD

**Issue by Saemy1** [Bouke/Lark#17]
I receive an parser error if I parse my wsdl
I tried to insert the WSDL from localhost and with a direct link from file system.

.build/debug/lark-generate-client "http://localhost:3001/Sales.wsdl" > Sources/Client.swift
fatal error: Error raised at top level: SchemaParser.ParseError.unsupportedType: file /Library/Caches/com.apple.xbs/Sources/swiftlang/swiftlang-800.0.63/src/swift/stdlib/public/core/ErrorType.swift, line 184
Current stack trace:
0    libswiftCore.dylib                 0x00000001086a4ce0 swift_reportError + 132
1    libswiftCore.dylib                 0x00000001086c1f70 _swift_stdlib_reportFatalErrorInFile + 112
2    libswiftCore.dylib                 0x0000000108670390 partial apply for (_assertionFailed(StaticString, String, StaticString, UInt, flags : UInt32) -> Never).(closure #1).(closure #1).(closure #1) + 99
3    libswiftCore.dylib                 0x00000001084b80c0 specialized specialized StaticString.withUTF8Buffer<A> ((UnsafeBufferPointer<UInt8>) -> A) -> A + 355
4    libswiftCore.dylib                 0x00000001086702d0 partial apply for (_assertionFailed(StaticString, StaticString, StaticString, UInt, flags : UInt32) -> Never).(closure #1).(closure #1) + 144
5    libswiftCore.dylib                 0x00000001084b85d0 specialized specialized String._withUnsafeBufferPointerToUTF8<A> ((UnsafeBufferPointer<UInt8>) throws -> A) throws -> A + 124
6    libswiftCore.dylib                 0x0000000108614b10 partial apply for (_assertionFailed(StaticString, String, StaticString, UInt, flags : UInt32) -> Never).(closure #1) + 185
7    libswiftCore.dylib                 0x00000001084b80c0 specialized specialized StaticString.withUTF8Buffer<A> ((UnsafeBufferPointer<UInt8>) -> A) -> A + 355
8    libswiftCore.dylib                 0x00000001084b7ea0 _assertionFailed(StaticString, String, StaticString, UInt, flags : UInt32) -> Never + 144
9    libswiftCore.dylib                 0x00000001084db560 swift_unexpectedError_merged + 569
10   lark-generate-client               0x0000000108141d40 main + 2504
11   libdyld.dylib                      0x00007fff91a3c254 start + 1
Illegal instruction: 4

**Comment by Bouke** [comment]
The current parser / generator don't support all xsd types possible. Can you share the wsdl? Or if that's not possible, run the code from Xcode and paste the xml snippet that's not supported? I'll then have a look and see what's needed to add support for that type.

**Comment by Bouke** [comment]
I've made quite a few improvements to the error reporting for the schema parsers. Although no additional syntax is handled, it should provide better diagnostics.

**Comment by Bouke** [comment]
Once you provide additional information we can further discuss this issue.
