### ISSUE TITLE
Lark in an iOS project

### ISSUE THREAD

**Issue by melcug** [Bouke/Lark#33]
Lark uses XMLDocument / XMLElement / XMLNode that are part of iOS’s Foundation, but just for macOS SDK and not for iOS SDK.

**Comment by melcug** [comment]
You can use in Lark project AEXML (Simple and lightweight XML parser written in Swift) that is compatible with all platforms (iOS, OS X, tvOS, watchOS).

**Comment by Bouke** [comment]
Thank you for looking into this. I wasn't aware of (NS)XMLDocument not being available on iOS. Sadly this library builds heavily on (NS)XMLDocument, I don't see that changing anytime soon. I would be open to patches that add support to other parsers, but I won't invest the time myself.
