### ISSUE TITLE
Error while getting the Library 

### ISSUE THREAD

**Issue by unosbaghaie** [Bouke/Lark#34]
Hi 
When I get your library, while getting there are some errors about Test projects that the suffix cannot be test. 
 then I build my swift project but again there are 20 errors and it doesn't build 
 second time I got different errors 

Last login: Sun May  7 15:12:45 on ttys002
Users-MacBook-Pro:modules User$ swift build
Fetching https://github.com/Bouke/Lark.git
Fetching https://github.com/Alamofire/Alamofire.git
Cloning https://github.com/Bouke/Lark.git
Resolving https://github.com/Bouke/Lark.git at 0.6.0
Cloning https://github.com/Alamofire/Alamofire.git
Resolving https://github.com/Alamofire/Alamofire.git at 4.4.0
xcrun: error: unable to lookup item 'PlatformPath' from command line tools installation
xcrun: error: unable to lookup item 'PlatformPath' in SDK '/Library/Developer/CommandLineTools/SDKs/MacOSX.sdk'
error: Invalid platform path
Users-MacBook-Pro:modules User$ 

what am I doing wrong ?

**Comment by unosbaghaie** [comment]
and now I get this error 

Users-MacBook-Pro:AdminPad2 User$ swift build
Cloning https://github.com/Bouke/Lark.git
HEAD is now at fc67970 Test against Linux (allow failure)
Resolved version: 0.6.0
Cloning https://github.com/Alamofire/Alamofire.git
HEAD is now at d1f0b86 Added release notes to the CHANGELOG and bumped the version to 4.4.0.
Resolved version: 4.4.0
error: the package has an unsupported layout, unexpected source file(s) found: /Users/User/Desktop/iOSCode/AdminPad2/package.swift
fix: move the file(s) inside a module
Users-MacBook-Pro:AdminPad2 User$

**Comment by Bouke** [comment]
Your package needs to be in a SwiftPM supported layout. If that's not possible, you could generate the code bindings outside of your project and then include the code and required dependencies by hand. Note that iOS is not supported, as it lacks NSXMLDocument.

**Comment by unosbaghaie** [comment]
Could you tell me how I can generate the code bindings outside of my project and then include the code and required dependencies by hand!?

**Comment by Bouke** [comment]
1. Generate the code outside of your project: see README. This requires SwiftPM.
2. Include the generated code dependencies by hand
    a. from step 1 you have generated code, paste it in a new file
    b. create/compile the "Alamofire" and "Lark" libraries in Xcode and mark them as a dependency
