### ISSUE TITLE
How to use it in a Xcode project?

### ISSUE THREAD

**Issue by zhouhao27** [Bouke/Lark#36]
Your library is looks what I need. But I don't know how to use it. Can I install your source code to my project from CocoaPods? Or any tutorial on how to integrate your code in an existing Swift project? Thanks.

**Comment by Bouke** [comment]
This package uses SwiftPM (Swift Package Manager), which you can use to build the command line tools and runtime library. See also #34 for a little more information. There is no support for CocoaPods at this moment.

**Comment by swiftnewbie** [comment]
I want to use the generated Client.swift file in my iOS Project, so I copied the Client.swift file in my project. The file uses 
  #import lark
and the compiler says "No such module Lark".
How to bind which files in XCode.
Can you help me, please?

**Comment by Bouke** [comment]
iOS is not going to work, sadly. (NS)XMLDocument not available on iOS. This library builds heavily on (NS)XMLDocument, I don't see that changing anytime soon. I would be open to discussion about using other parsers, but I won't invest the time myself on switching this library over.
